name: sync2mirror
on:
  push:
    branches:
      - master
      - dev
jobs:
  repo-sync:
    env:
      gitcode_key: ${{ secrets.GITCODE_PRIVATE_KEY }}
      gitcode_token: ${{ secrets.GITCODE_TOKEN }}
      gitcode_user: ${{ secrets.GITCODE_USER }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Mask sensitive values
        run: |
          echo "::add-mask::${{ github.repository_owner }}"
          echo "::add-mask::${{ github.event.repository.name }}"

      - name: sync
        uses: Yikun/hub-mirror-action@master
        if: env.gitcode_key && env.gitcode_token && env.gitcode_user
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitcode/${{ secrets.GITCODE_USER }}'
          dst_key: ${{ secrets.GITCODE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITCODE_TOKEN }}
          account_type: user
          static_list: ${{ github.event.repository.name }}
          force_update: true
